/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package excal;

import org.junit.Test;
import static org.junit.Assert.*;

public class ExcalTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Excal classUnderTest = new Excal();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
