/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.damonyuan.tcal;

import org.junit.Test;
import static org.junit.Assert.*;

public class tcalTest {
    @Test public void someLibraryMethodReturnsTrue() {
        assertEquals("1.0.0", Tcal.getVersion());
    }
}
