/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.damonyuan.tcal;

import org.junit.Test;
import static org.junit.Assert.*;

public class tcalTest {
    @Test public void someLibraryMethodReturnsTrue() {
        tcal classUnderTest = new tcal();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
